### ISSUE TITLE
Can't find the .yaml of OCHuman

### ISSUE THREAD

**Issue by zhexiangrenjian** [cherubicXN/logocap#3]

**Comment by zhexiangrenjian** [comment]
Hi, Thank you for the amazing work!
Could you please release the .YAML files of OCHuman？

**Comment by cherubicXN** [comment]
Actually, I did not create a YAML file for OCHuman as we did not do the training on this dataset and the format is the same as COCO. So, as long as you downloaded (and uncompressed) the OCHuman dataset  in the ``data`` directory with the name ``ochuman``, you can make the inference by 
```
python tools/test.py --cfg experiments/logocap-hrnet-w32-coco.yaml \
 --ckpt weights/logocap/logocap-hrnet-w32-coco.pth.tar  \
DATASET.TEST {split} DATASET.ROOT data/ochuman
```
where ``{split}`` is "eval" for the testing split and "val" for the validation split.

It should be noted that I replaced the split name of testing from "test" to "eval" to avoid a conflict with the COCO test-dev dataset that doesn't have ground truth for offline evaluation.

Changing the following lines 
https://github.com/cherubicXN/logocap/blob/39d104fdaf4970bab91392fe81897e450daaffb9/experiments/logocap-hrnet-w32-coco.yaml#L27-L28
also works.
