### ISSUE TITLE
Request for full OChuman val/test results (AP & AR)

### ISSUE THREAD

**Issue by yangjie-cv** [cherubicXN/logocap#4]
Hi, Thank you for the amazing work!
Could you please release the full results on OChuman val/test including AP & AR？

**Comment by cherubicXN** [comment]
# LOGOCAP-W32 
<details> <summary> Results on the OCHuman Valitation</summary>

 - Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.390
 - Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.517
 - Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.435
 - Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.089
 - Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.409
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.748
 - Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.935
 - Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.815
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.629
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.748

</details>

<details> <summary> Results on the OCHuman Testing</summary>

 - Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.381
 - Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.506
 - Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.421
 - Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 - Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.403
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.745
 - Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.938
 - Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.805
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
 - Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.745

</details>

# LOGOCAP-W48
<details> <summary> Results on the OCHuman Valitation</summary>

- Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.412
- Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.528
- Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.457
- Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.045
- Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.430
- Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.776
- Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.947
- Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.841
- Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.600
- Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.776

</details>

<details> <summary> Results on the OCHuman Testing</summary>

- Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.404
- Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.519
- Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.446
- Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
- Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.426
- Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.775
- Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.950
- Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.838
- Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = -1.000
- Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets= 20 ] = 0.775
</details>

**Comment by cherubicXN** [comment]
@yangjie-cv Hi, I have posted the full results of the OCHuman val/test evaluations.

I tried to find the log for the results of the compared approaches but did not find it as I have cleaned some large-volume data from my machine.
